[project]
name = "dependency-test"
authors = []
description = ""
telemetry = true
requirements = []

boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.first-contract]
path = "contracts/first-contract.clar"

[contracts.second-contract]
path = "contracts/second-contract.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
